### ISSUE TITLE
nanodet代码问题

### ISSUE THREAD

**Issue by FengMu1995** [FeiGeChuanShu/ncnn_Android_RobustVideoMatting#4]
为什么是两个原图输入
ncnn_in = ncnn::Mat::from_pixels_resize(rgb.data,ncnn::Mat::PIXEL_RGB, rgb.cols, rgb.rows,512,512);//
 ncnn_in1 = ncnn::Mat::from_pixels_resize(rgb.data,ncnn::Mat::PIXEL_RGB, rgb.cols, rgb.rows,256,256);
 ex_face.input("src1", ncnn_in1);
 ex_face.input("src2", ncnn_in);

**Comment by FeiGeChuanShu** [comment]
@FengMu1995 因为源代码中是不同分辨率的输入预处理不一样，为了方便预处理就改成了两个输入，当然也可以改成一个输入，后处理在网络中进行
